### ISSUE TITLE
after build make -f ./sp_make.mk

### ISSUE THREAD

**Issue by maku0** [tibbotech/yocto_layers#8] opened 2020-05-21 09:26 UTC
km@ubuntu:/disk2/build.24/tmp/deploy/images/tppg2$ make -f ./sp_make.mk
install -d ./sp_out/
install ../tppg2-arm5/xboot-emmc.bin ./sp_out/xboot.bin
./sp_tools/secure_sign/gen_signature.sh ./sp_out xboot.bin 0
**************************************
*** Warning: Sign with TEST key !! ***
*** Please put real keys in keys/. ***
**************************************
Private key: ./sp_tools/secure_sign/sign_keys/test-keys/key_priv_0.hex
Public key : ./sp_tools/secure_sign/sign_keys/test-keys/key_pub_0.hex
Sign and verify signature OK.
key_pub    : 0xAC, 0xE4, 0x68, 0x98, 0x89, 0x68, 0x75, 0x2B, 0x91, 0x61, 0xF7, 0x3F, 0x9B, 0x72, 0x98, 0x34, 0xA8, 0xF5, 0x68, 0xE1, 0xA2, 0x05, 0x60, 0x0F, 0x7D, 0xDE, 0xBC, 0xCE, 0xDE, 0x87, 0x40, 0x5C
Signature  : 0x7B, 0x9E, 0x23, 0x74, 0x91, 0x83, 0x8A, 0x51, 0xC3, 0xE2, 0x9A, 0x4D, 0x34, 0x7A, 0x33, 0x2C, 0xCA, 0x45, 0xBA, 0xEB, 0xDA, 0x80, 0xB2, 0x95, 0xE4, 0x92, 0x94, 0xDF, 0x81, 0xB9, 0x52, 0x9E, 0x93, 0xE6, 0x73, 0xF2, 0xC5, 0x1F, 0x56, 0x82, 0x11, 0x6D, 0x17, 0x63, 0xD0, 0x94, 0xA5, 0x24, 0x64, 0x8D, 0xA6, 0x42, 0xA2, 0x39, 0x04, 0xD5, 0xB5, 0xC0, 0xC7, 0x49, 0xB4, 0x13, 0x90, 0x03

Save signature to file: ./sp_out/sign.sig
no need to add sign flag (xboot)
OUT_SIG: ./sp_out/sign.sig
IN_IMG: ./sp_out/xboot.bin
cd ../tppg2-arm5/sp_tools/; ./add_xhdr.sh ../../tppg2/sp_out/xboot.bin ../../tppg2/sp_out/xboot.img 1
chksum=0000e265
install ./sp_out/xboot.img ./sp_out/xboot0
install ./sp_out/xboot.img ./sp_out/xboot1
install -d ./sp_out/
export MKIMAGE=./sp_tools/mkimage
./sp_tools/add_uhdr.sh nonos_B ../tppg2-arm5/a926.bin sp_out/nonos 0x10040 0x10040
**./sp_tools/add_uhdr.sh: line 68: ./boot/uboot/tools/mkimage: No such file or directory
ls: cannot access 'sp_out/nonos': No such file or directory**
sp_make.mk:48: recipe for target 'sp_out/nonos' failed
make: *** [sp_out/nonos] Error 2
km@ubuntu:/disk2/build.24/tmp/deploy/images/tppg2$ 

I dont have sp_out/nonos, and I dont have ./boot/uboot/tools/mkimage, instead I have tppg2/sp_tools/mkimage and tppg2-arm5/sp_tools/mkimage

**Comment by dmitrydvorkin** [comment] 2020-05-27 10:28
The problem is in export MKIMAGE=... it has to be i the same line with add_uhdr:
export MKIMAGE=./sp_tools/mkimage; ./sp_tools/add_uhdr.sh ....

It is fixed internally, but not released yet. There are more fixes upcoming, sorry.

**Comment by erimsa** [comment] 2020-05-27 19:00
@maku0  export MKIMAGE before running sp_make.mk script  while waiting new coming fixes. Desribed below ; 

export MKIMAGE=./sp_tools/mkimage

**Comment by maku0** [comment] 2020-05-28 10:13
It works, thanks. Last suggestion in sp_make.mk is constant F_ROO=img-tps-base-tppg2.ext4, name for default yocto rootfs image is diferent.

**Closed as completed** 2020-05-28 10:13 UTC

**Comment by dmitrydvorkin** [comment] 2020-06-10 23:33
Dear maku0 and erimsa!
Did you get notification about Tibbo_Layers update?
There are several issues fixed (including improvements on already answered tickets).
Dear ErimSa! I'd recommend you to add yourself to "watchers" list :)

https://github.com/tibbotech/yocto_layers/commit/dc1c4283593af77d5d7ad640ec6f3909d6e1f005

New -base firmware
https://tibbo.com/downloads/LTPS/FW/LTPPg2/
please, see changelog.txt

new BA:
https://tibbo.com/downloads/LTPS/BuildAppliance/
please, see changelog.txt

Repo and SDK (3.0.2) is updated too. But no significant changes.
